version 2.1
Changes:

 * bashrc: fixes for help message printed on bash
   login.

 * installer: fix error when Termux VM is not installed
   and update dpkg binaries in bootstrap archive.

 * qemu-mon: show warning when qemu monitor socket
   is not found.

 * sshd_config: enable 'curve25519-sha256@libssh.org'
   in KexAlgorithms. Fixes error when connecting from
   the VM to the host.

 * termux-container: embed proot executable into
   script.

 * tmux: add missing configuration file.

diff --git a/package-files/data/data/com.termux/files/usr/bin/qemu-mon b/package-files/data/data/com.termux/files/usr/bin/qemu-mon
--- a/package-files/data/data/com.termux/files/usr/bin/qemu-mon
+++ b/package-files/data/data/com.termux/files/usr/bin/qemu-mon
@@ -1,5 +1,11 @@
 #!/data/data/com.termux/files/usr/bin/sh
-[ -z "${PREFIX}" ] && export PREFIX="/data/data/com.termux/files/usr"
+[ -z "${TMPDIR}" ] && export TMPDIR="/data/data/com.termux/files/usr/tmp"
 
-echo "[*] Connecting to the QEMU monitor... "
-exec socat - "UNIX-CONNECT:${PREFIX}/tmp/qemu-mon"
+if [ -S "${TMPDIR}/qemu-mon" ]; then
+    echo "[*] Connecting to the QEMU monitor... "
+    exec socat - "UNIX-CONNECT:${PREFIX}/tmp/qemu-mon"
+else
+    echo "[*] QEMU Monitor socket is not found."
+    echo "    Possible that QEMU session is not running."
+    exit 1
+fi
